server:
  port: 9292
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/martfury
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: jcache
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
      javax:
        cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          uri: classpath:ehcache.xml
    show-sql: true
  main:
    allow-bean-definition-overriding: true